config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'new_user/new'
  resources :users , :stories
  root 'home#index'
  # resources :stories
  get 'stories', to: 'stories#index'
  get 'sign_up', to: 'new_user#new'
  post 'sign_up', to: 'new_user#create'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes

    attribute :user
  
  end

app/models/story.rb
class Story < ApplicationRecord
    belongs_to :user
    # validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :stories
    has_secure_password
    validates :email, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper  
  before_action :set_current_user


    def set_current_user
      if session[:user_id]
       Current.user = User.find_by(id: session[:user_id])
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/new_user_controller.rb
class NewUserController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "Welcome to the app!"
      session[:user_id] = @user.id
      redirect_to root_path
      else
       render :new  
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user.present? && user.authenticate(params[:password])
       session[:user_id] = user.id
       redirect_to root_path
    else
        flash.now[:danger] = 'Invalid email/password combination'
        render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to sign_in_path
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: %i[ show edit update destroy ]

  # GET /stories or /stories.json
  def index
    @stories = Story.all
  end

  # GET /stories/1 or /stories/1.json
  def show
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories or /stories.json
  def create
    @story = Story.new(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to story_url(@story), notice: "Story was successfully created." }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1 or /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to story_url(@story), notice: "Story was successfully updated." }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1 or /stories/1.json
  def destroy
    @story.destroy

    respond_to do |format|
      format.html { redirect_to stories_url, notice: "Story was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def story_params
      params.require(:story).permit(:title, :picture, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :log_in, only: [:show]
    def show
      @user = User.find(params[:id])
    end
  
    def new
      @user = User.new
    end
  
    def create
      @user = User.new(user_params)
      if @user.save
        flash[:success] = "Welcome to the app!"
        redirect_to root_path
      else
        render 'new'
      end
    end
  
    private
  
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/new_user_helper.rb
module NewUserHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
      session[:user_id] = user.id
    end
  
    def current_user
      if session[:user_id]
        @current_user ||= User.find_by(id: session[:user_id])
      end
    end
  
    def logged_in?
      !current_user.nil?
    end
  
    def log_out
      session.delete(:user_id)
      @current_user = nil
    end
  
    def current_user?(user)
      user == current_user
    end
  
    def redirect_back_or(default)
      redirect_to(session[:forwarding_url] || default)
      session.delete(:forwarding_url)
    end
  
    def store_location
      session[:forwarding_url] = request.original_url if request.get?
    end
  end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<% if Current.user %>
  <%= button_to "Sign Out", logout_path,  method: :delete %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="dark">
  <head>
    <title>ManualJam</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css">
    <%= javascript_importmap_tags %>
    <nav class="navbar mb-2">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to "Home", root_path, class: "mx-2" %>
        </div>


        <% if logged_in? %>
          Logged in as: <%=Current.user.name%>
          <div class="navbar-header">
            <%= link_to "Stories", stories_path, class: "mx-2" %>
          </div>
          <ul class="nav navbar-right ">
            <li><%= link_to "Log out", logout_path, class: "mx-2", method: :delete %></li> 
          </ul>
        <% else %>
          <ul class="nav navbar-right ">
            <li><%= link_to "Log in", sign_in_path, class: "mx-2" %></li> 
            <li><%= link_to "Sign up", sign_up_path, class: "mx-2" %></li>
          </ul>
        <% end %>
      </div>
    </nav>
  </head>
  <body>
    <main class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/new_user/new.html.erb
<h1>Create new user</h1>
<%= form_with model: @user, url: sign_up_path do |f|  %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "Sign Up" %>
<% end %>

app/views/stories/_form.html.erb
<%= form_with(model: story) do |form| %>
  <% if story.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
        <% story.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :picture, style: "display: block" %>
    <%= form.text_field :picture %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/stories/_story.html.erb
<div id="<%= dom_id story %>">
  <p>
    <strong>Title:</strong>
    <%= story.title %>
  </p>

  <p>
    <strong>Picture:</strong>
    <%= story.picture %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= story.content %>
  </p>

</div>

app/views/stories/edit.html.erb
<h1>Editing story</h1>

<%= render "form", story: @story %>

<br>

<div>
  <%= link_to "Show this story", @story %> |
  <%= link_to "Back to stories", stories_path %>
</div>

app/views/stories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Stories</h1>

<div id="stories">
  <% @stories.each do |story| %>
    <%= render story %>
    <p>
      <%= link_to "Show this story", stories_path %>
    </p>
  <% end %>
</div>

<%= link_to "New story", new_story_path %>

app/views/stories/new.html.erb
<h1>New story</h1>

<%= render "form", story: @story %>

<br>

<div>
  <%= link_to "Back to stories", stories_path %>
</div>

app/views/stories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @story %>

<div>
  <%= link_to "Edit this story", edit_story_path(@story) %> |
  <%= link_to "Back to stories", stories_path %>

  <%= button_to "Destroy this story", @story, method: :delete %>
</div>

app/views/users/new.html.erb
<h1 class='text-center'>Sign up</h1>

<div class="row">
  <div class="col-md-4 offset-4">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'mb-1 form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'mb-1 form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'mb-1 form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'mb-1 form-control' %>

      <%= f.submit "Create my account", class: "mt-2 btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="offset-4 col-md-4">
      <h3 class='text-center'>
        <%= @user.name %>
      </h3>
      <h3 class='text-center'>
        <%= @user.email %>
      </h3>
  </div>
</div>